# Generated by Django 5.2.12 on 2026-03-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatuslog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
