# Generated by Django 5.2.12 on 2026-04-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_department'),
        ('tickets', '0008_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_assigned', to='companies.department'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_created', to='companies.department'),
        ),
    ]
