services:
  db:
    image: postgres:16
    volumes:
      - flux_prod_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 3s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend/flux
    command: gunicorn flux.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./backend/flux:/usr/src/flux
    env_file:
      - .env.prod
    depends_on:
      - redis
      - db

  daphne:
    build:
      context: ./backend/flux
    command: daphne -b 0.0.0.0 -p 8001 flux.asgi:application
    volumes:
      - ./backend/flux:/usr/src/flux
    env_file:
      - .env.prod
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env.local.prod
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/flux/staticfiles:/usr/src/flux/staticfiles:ro 
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend

volumes:
  flux_prod_postgres_data: