services:
  db:
    image: postgres:16
    volumes:
      - flux_dev_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend/flux
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/flux:/usr/src/flux
      - ./frontend/public:/usr/src/flux/frontend_static:ro
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.local.dev
    ports:
      - "3000:3000"

volumes:
  flux_dev_postgres_data: