# Generated by Django 5.2.12 on 2026-04-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_created_by'),
        ('companies', '0004_department'),
        ('tickets', '0009_alter_ticket_assigned_to_alter_ticket_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
