import csv
from io import BytesIO
from django.http import HttpResponse
from django.utils import timezone
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

class ReportService:
    @staticmethod
    def generate_csv_report(queryset, user):
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="tickets_report.csv"'

        writer = csv.writer(response)
        writer.writerow(["Report:", "FLUX IT Tickets", "", "", "", ""])
        writer.writerow(["Generated by:", user.name, "", "", "", ""])
        writer.writerow(["Date:", timezone.now().strftime('%d-%m-%Y %H:%M'), "", "", "", ""])
        writer.writerow([]) 
        writer.writerow(["Ticket Number", "From Dept", "To Dept", "Priority", "Status", "Created At"])

        for ticket in queryset:
            writer.writerow([
                ticket.ticket_number,
                ticket.department.name,
                ticket.assigned_to.name,
                ticket.get_priority_display(),
                ticket.get_status_display(),
                ticket.created_at.strftime('%d-%m-%Y %H:%M')
            ])
        return response

    @staticmethod
    def generate_pdf_report(queryset, user, department_filter, department_filter_name, start_date, end_date):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
        elements = []
        styles = getSampleStyleSheet()

        # Custom Styles (Simplified for brevity, use your existing hex-color styles here)
        title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, textColor=colors.HexColor('#2C3E50'), alignment=1)
        header_info = ParagraphStyle('Info', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#34495E'))
        table_header = ParagraphStyle('THeader', parent=styles['Normal'], fontSize=9, textColor=colors.white, alignment=1, fontName='Helvetica-Bold')
        cell_style = ParagraphStyle('TCell', parent=styles['Normal'], fontSize=8)

        # Build Header
        elements.append(Paragraph("FLUX Ticket Report", title_style))
        elements.append(Spacer(1, 0.1*inch))
        elements.append(HRFlowable(width="100%", thickness=2, color=colors.navy))
        
        # Meta Table
        meta_data = [
            [Paragraph(f"<b>Generated by:</b> {user.name} ({user.department.name})", header_info),
             Paragraph(f"<b>Report Dept:</b> {department_filter_name if department_filter_name else 'All'}", header_info)],
            [Paragraph(f"<b>Date:</b> {timezone.now().strftime('%d-%m-%Y %H:%M')}", header_info),
             Paragraph(f"<b>Range:</b> {start_date.strftime('%d-%m-%Y') if start_date else 'All'} to {end_date.strftime('%d-%m-%Y') if end_date else 'All'}", header_info)]
        ]
        meta_table = Table(meta_data, colWidths=[doc.width/2.0]*2)
        elements.append(meta_table)
        elements.append(Spacer(1, 0.3*inch))

        # Table Construction
        data = [[Paragraph(h, table_header) for h in ["Ticket #", "From Dept", "To Dept", "Priority", "Status", "Created"]]]
        
        for ticket in queryset:
            data.append([
                ticket.ticket_number,
                ticket.department.name,
                ticket.assigned_to.name,
                ticket.get_priority_display(),
                ticket.get_status_display(),
                ticket.created_at.strftime('%d-%m-%Y %H:%M')
            ])

        table = Table(data, colWidths=[0.15*doc.width, 0.18*doc.width, 0.18*doc.width, 0.12*doc.width, 0.12*doc.width, 0.25*doc.width])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.navy),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#BDC3C7')),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#F8F9F9')]),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        elements.append(table)

        doc.build(elements)
        buffer.seek(0)
        
        filename = f"tickets_report_{timezone.now().strftime('%Y%m%d_%H%M')}.pdf"
        response = HttpResponse(buffer, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

    @staticmethod
    def generate_single_ticket_pdf(ticket):
        buffer = BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=50,
            rightMargin=50,
            topMargin=60,
            bottomMargin=50
        )

        elements = []
        styles = getSampleStyleSheet()

        # ---------------- CUSTOM STYLES ----------------
        title_style = ParagraphStyle(
            'TitleStyle',
            parent=styles['Heading1'],
            fontSize=22,
            textColor=colors.HexColor('#1F2937'),
            alignment=1,  # center
            spaceAfter=10
        )

        meta_style = ParagraphStyle(
            'MetaStyle',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            spaceAfter=2
        )

        section_header = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=13,
            textColor=colors.HexColor('#111827'),
            spaceBefore=18,
            spaceAfter=10
        )

        label_style = ParagraphStyle(
            'LabelStyle',
            parent=styles['Normal'],
            fontSize=10,
            fontName='Helvetica-Bold',
            textColor=colors.HexColor('#374151')
        )

        value_style = ParagraphStyle(
            'ValueStyle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#1F2937')
        )

        # ---------------- HEADER ----------------
        elements.append(Paragraph("FLUX Ticket Report", title_style))

        elements.append(Paragraph(
            f"Ticket Number: {ticket.ticket_number}",
            meta_style
        ))

        elements.append(Paragraph(
            f"Generated: {timezone.now().strftime('%d %B %Y, %H:%M')}",
            meta_style
        ))

        elements.append(Spacer(1, 18))

        # ---------------- CORE DETAILS SECTION ----------------
        elements.append(Paragraph("Ticket Information", section_header))

        details_data = [
            [Paragraph("Title", label_style), Paragraph(ticket.title, value_style)],
            [Paragraph("Priority", label_style), Paragraph(ticket.get_priority_display(), value_style)],
            [Paragraph("Status", label_style), Paragraph(ticket.get_status_display(), value_style)],
            [Paragraph("From Department", label_style), Paragraph(ticket.department.name, value_style)],
            [Paragraph("Assigned To", label_style), Paragraph(ticket.assigned_to.name, value_style)],
            [Paragraph("Created At", label_style), Paragraph(ticket.created_at.strftime('%d-%m-%Y %H:%M'), value_style)],
        ]

        details_table = Table(details_data, colWidths=[doc.width * 0.3, doc.width * 0.7])
        details_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('INNERGRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))

        elements.append(details_table)

        elements.append(Spacer(1, 16))

        # ---------------- DESCRIPTION ----------------
        elements.append(Paragraph("Description", section_header))

        elements.append(
            Table(
                [[Paragraph(ticket.description or "No description provided.", value_style)]],
                colWidths=[doc.width]
            )
        )

        elements.append(Spacer(1, 18))

        # ---------------- STATUS HISTORY ----------------
        elements.append(Paragraph("Status History", section_header))

        logs = ticket.status_logs.all().select_related('changed_by')

        if logs.exists():
            log_data = [[
                Paragraph("<b>Old Status</b>", value_style),
                Paragraph("<b>New Status</b>", value_style),
                Paragraph("<b>Changed By</b>", value_style),
                Paragraph("<b>Date/Time</b>", value_style),
            ]]

            for log in logs:
                log_data.append([
                    Paragraph(log.old_status.replace('_', ' ').title(), value_style),
                    Paragraph(log.new_status.replace('_', ' ').title(), value_style),
                    Paragraph(log.changed_by.name if log.changed_by else "System", value_style),
                    Paragraph(log.changed_at.strftime('%d-%m-%Y %H:%M'), value_style),
                ])

            log_table = Table(
                log_data,
                colWidths=[doc.width * 0.25, doc.width * 0.25, doc.width * 0.25, doc.width * 0.25],
                repeatRows=1
            )

            log_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#D4D4D4")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1),
                [colors.whitesmoke, colors.transparent]),
                ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))

            elements.append(log_table)

        else:
            elements.append(Paragraph(
                "No status changes recorded for this ticket.",
                value_style
            ))

        # ---------------- FOOTER ----------------
        elements.append(Spacer(1, 25))

        elements.append(Paragraph(
            "Generated by FLUX Ticketing System",
            meta_style
        ))

        doc.build(elements)
        buffer.seek(0)

        filename = f"Ticket_{ticket.ticket_number}_Details.pdf"
        response = HttpResponse(buffer, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename=\"{filename}\"'
        return response